[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.17"
bytecode_hash = "none"
optimizer = true
via_ir = true
optimizer_runs = 1000000
no_match_path = "*/integration/*"
fuzz_runs = 10000
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

#[profile.dependencies]
#"@openzeppelin/contracts" = "git+https://github.com/OpenZeppelin/openzeppelin-contracts.git"